// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: sandbox/v1/sandbox.proto

package v1

import (
	common "agent/sandbox/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifeCycle int32

const (
	LifeCycle_LIFECYCLE_UNKNOWN LifeCycle = 0
	LifeCycle_LIFECYCLE_ALWAYS  LifeCycle = 1
	LifeCycle_LIFECYCLE_ONCE    LifeCycle = 2
)

// Enum value maps for LifeCycle.
var (
	LifeCycle_name = map[int32]string{
		0: "LIFECYCLE_UNKNOWN",
		1: "LIFECYCLE_ALWAYS",
		2: "LIFECYCLE_ONCE",
	}
	LifeCycle_value = map[string]int32{
		"LIFECYCLE_UNKNOWN": 0,
		"LIFECYCLE_ALWAYS":  1,
		"LIFECYCLE_ONCE":    2,
	}
)

func (x LifeCycle) Enum() *LifeCycle {
	p := new(LifeCycle)
	*p = x
	return p
}

func (x LifeCycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifeCycle) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_v1_sandbox_proto_enumTypes[0].Descriptor()
}

func (LifeCycle) Type() protoreflect.EnumType {
	return &file_sandbox_v1_sandbox_proto_enumTypes[0]
}

func (x LifeCycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifeCycle.Descriptor instead.
func (LifeCycle) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

type SandboxState int32

const (
	SandboxState_SANDBOX_STATE_UNKNOWN  SandboxState = 0
	SandboxState_SANDBOX_STATE_CREATING SandboxState = 1
	SandboxState_SANDBOX_STATE_RUNNING  SandboxState = 2
	SandboxState_SANDBOX_STATE_DELETING SandboxState = 3
	SandboxState_SANDBOX_STATE_DELETED  SandboxState = 4
	SandboxState_SANDBOX_STATE_ERROR    SandboxState = 5
)

// Enum value maps for SandboxState.
var (
	SandboxState_name = map[int32]string{
		0: "SANDBOX_STATE_UNKNOWN",
		1: "SANDBOX_STATE_CREATING",
		2: "SANDBOX_STATE_RUNNING",
		3: "SANDBOX_STATE_DELETING",
		4: "SANDBOX_STATE_DELETED",
		5: "SANDBOX_STATE_ERROR",
	}
	SandboxState_value = map[string]int32{
		"SANDBOX_STATE_UNKNOWN":  0,
		"SANDBOX_STATE_CREATING": 1,
		"SANDBOX_STATE_RUNNING":  2,
		"SANDBOX_STATE_DELETING": 3,
		"SANDBOX_STATE_DELETED":  4,
		"SANDBOX_STATE_ERROR":    5,
	}
)

func (x SandboxState) Enum() *SandboxState {
	p := new(SandboxState)
	*p = x
	return p
}

func (x SandboxState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxState) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_v1_sandbox_proto_enumTypes[1].Descriptor()
}

func (SandboxState) Type() protoreflect.EnumType {
	return &file_sandbox_v1_sandbox_proto_enumTypes[1]
}

func (x SandboxState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxState.Descriptor instead.
func (SandboxState) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{1}
}

type SandBoxType int32

const (
	SandBoxType_SANDBOX_TYPE_Base    SandBoxType = 0
	SandBoxType_SANDBOX_TYPE_FS      SandBoxType = 1
	SandBoxType_SANDBOX_TYPE_BROWSER SandBoxType = 2
	SandBoxType_SANDBOX_TYPE_CUSTOM  SandBoxType = 3
)

// Enum value maps for SandBoxType.
var (
	SandBoxType_name = map[int32]string{
		0: "SANDBOX_TYPE_Base",
		1: "SANDBOX_TYPE_FS",
		2: "SANDBOX_TYPE_BROWSER",
		3: "SANDBOX_TYPE_CUSTOM",
	}
	SandBoxType_value = map[string]int32{
		"SANDBOX_TYPE_Base":    0,
		"SANDBOX_TYPE_FS":      1,
		"SANDBOX_TYPE_BROWSER": 2,
		"SANDBOX_TYPE_CUSTOM":  3,
	}
)

func (x SandBoxType) Enum() *SandBoxType {
	p := new(SandBoxType)
	*p = x
	return p
}

func (x SandBoxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandBoxType) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_v1_sandbox_proto_enumTypes[2].Descriptor()
}

func (SandBoxType) Type() protoreflect.EnumType {
	return &file_sandbox_v1_sandbox_proto_enumTypes[2]
}

func (x SandBoxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandBoxType.Descriptor instead.
func (SandBoxType) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{2}
}

type RuntimeType int32

const (
	RuntimeType_RUNTIME_TYPE_Containerd RuntimeType = 0
	RuntimeType_RUNTIME_TYPE_DOCKER     RuntimeType = 1
	RuntimeType_RUNTIME_TYPE_K8S        RuntimeType = 2
)

// Enum value maps for RuntimeType.
var (
	RuntimeType_name = map[int32]string{
		0: "RUNTIME_TYPE_Containerd",
		1: "RUNTIME_TYPE_DOCKER",
		2: "RUNTIME_TYPE_K8S",
	}
	RuntimeType_value = map[string]int32{
		"RUNTIME_TYPE_Containerd": 0,
		"RUNTIME_TYPE_DOCKER":     1,
		"RUNTIME_TYPE_K8S":        2,
	}
)

func (x RuntimeType) Enum() *RuntimeType {
	p := new(RuntimeType)
	*p = x
	return p
}

func (x RuntimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_v1_sandbox_proto_enumTypes[3].Descriptor()
}

func (RuntimeType) Type() protoreflect.EnumType {
	return &file_sandbox_v1_sandbox_proto_enumTypes[3]
}

func (x RuntimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeType.Descriptor instead.
func (RuntimeType) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{3}
}

type CreateSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the sandbox, e.g. "fs", "browser", etc.
	SandboxType SandBoxType `protobuf:"varint,3,opt,name=sandbox_type,json=sandboxType,proto3,enum=sandbox.v1.SandBoxType" json:"sandbox_type,omitempty"`
	// The configuration of the sandbox, which is a JSON string.
	Config        *Config `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSandboxRequest) GetSandboxType() SandBoxType {
	if x != nil {
		return x.SandboxType
	}
	return SandBoxType_SANDBOX_TYPE_Base
}

func (x *CreateSandboxRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateSandboxResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Data          *CreateSandboxResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status        *common.Status              `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSandboxResponse) GetData() *CreateSandboxResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateSandboxResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeleteSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxRequest) Reset() {
	*x = DeleteSandboxRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxRequest) ProtoMessage() {}

func (x *DeleteSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxRequest.ProtoReflect.Descriptor instead.
func (*DeleteSandboxRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type DeleteSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxResponse) Reset() {
	*x = DeleteSandboxResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxResponse) ProtoMessage() {}

func (x *DeleteSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxResponse.ProtoReflect.Descriptor instead.
func (*DeleteSandboxResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSandboxResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetSandboxStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxStatusRequest) Reset() {
	*x = GetSandboxStatusRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxStatusRequest) ProtoMessage() {}

func (x *GetSandboxStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxStatusRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *GetSandboxStatusRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type GetSandboxStatusResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Data          *GetSandboxStatusResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status        *common.Status                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxStatusResponse) Reset() {
	*x = GetSandboxStatusResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxStatusResponse) ProtoMessage() {}

func (x *GetSandboxStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxStatusResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *GetSandboxStatusResponse) GetData() *GetSandboxStatusResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetSandboxStatusResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetSandboxTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxTypesRequest) Reset() {
	*x = GetSandboxTypesRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxTypesRequest) ProtoMessage() {}

func (x *GetSandboxTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxTypesRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxTypesRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{6}
}

type GetSandboxTypesResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Data          *GetSandboxTypesResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status        *common.Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxTypesResponse) Reset() {
	*x = GetSandboxTypesResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxTypesResponse) ProtoMessage() {}

func (x *GetSandboxTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxTypesResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxTypesResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *GetSandboxTypesResponse) GetData() *GetSandboxTypesResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetSandboxTypesResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeType   RuntimeType            `protobuf:"varint,1,opt,name=runtimeType,proto3,enum=sandbox.v1.RuntimeType" json:"runtimeType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *Config) GetRuntimeType() RuntimeType {
	if x != nil {
		return x.RuntimeType
	}
	return RuntimeType_RUNTIME_TYPE_Containerd
}

type CreateSandboxResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	State         SandboxState           `protobuf:"varint,2,opt,name=state,proto3,enum=sandbox.v1.SandboxState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse_Data) Reset() {
	*x = CreateSandboxResponse_Data{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse_Data) ProtoMessage() {}

func (x *CreateSandboxResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse_Data.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse_Data) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateSandboxResponse_Data) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSandboxResponse_Data) GetState() SandboxState {
	if x != nil {
		return x.State
	}
	return SandboxState_SANDBOX_STATE_UNKNOWN
}

type GetSandboxStatusResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         SandboxState           `protobuf:"varint,1,opt,name=state,proto3,enum=sandbox.v1.SandboxState" json:"state,omitempty"`
	SandboxId     string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	SandboxType   SandBoxType            `protobuf:"varint,3,opt,name=sandbox_type,json=sandboxType,proto3,enum=sandbox.v1.SandBoxType" json:"sandbox_type,omitempty"`
	Config        *Config                `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxStatusResponse_Data) Reset() {
	*x = GetSandboxStatusResponse_Data{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxStatusResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxStatusResponse_Data) ProtoMessage() {}

func (x *GetSandboxStatusResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxStatusResponse_Data.ProtoReflect.Descriptor instead.
func (*GetSandboxStatusResponse_Data) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetSandboxStatusResponse_Data) GetState() SandboxState {
	if x != nil {
		return x.State
	}
	return SandboxState_SANDBOX_STATE_UNKNOWN
}

func (x *GetSandboxStatusResponse_Data) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *GetSandboxStatusResponse_Data) GetSandboxType() SandBoxType {
	if x != nil {
		return x.SandboxType
	}
	return SandBoxType_SANDBOX_TYPE_Base
}

func (x *GetSandboxStatusResponse_Data) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetSandboxStatusResponse_Data) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetSandboxStatusResponse_Data) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetSandboxStatusResponse_Data) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetSandboxTypesResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxTypes  []SandBoxType          `protobuf:"varint,1,rep,packed,name=sandbox_types,json=sandboxTypes,proto3,enum=sandbox.v1.SandBoxType" json:"sandbox_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxTypesResponse_Data) Reset() {
	*x = GetSandboxTypesResponse_Data{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxTypesResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxTypesResponse_Data) ProtoMessage() {}

func (x *GetSandboxTypesResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxTypesResponse_Data.ProtoReflect.Descriptor instead.
func (*GetSandboxTypesResponse_Data) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetSandboxTypesResponse_Data) GetSandboxTypes() []SandBoxType {
	if x != nil {
		return x.SandboxTypes
	}
	return nil
}

var File_sandbox_v1_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_v1_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x18sandbox/v1/sandbox.proto\x12\n" +
	"sandbox.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x13common/common.proto\"~\n" +
	"\x14CreateSandboxRequest\x12:\n" +
	"\fsandbox_type\x18\x03 \x01(\x0e2\x17.sandbox.v1.SandBoxTypeR\vsandboxType\x12*\n" +
	"\x06config\x18\x04 \x01(\v2\x12.sandbox.v1.ConfigR\x06config\"\xd2\x01\n" +
	"\x15CreateSandboxResponse\x12:\n" +
	"\x04data\x18\x01 \x01(\v2&.sandbox.v1.CreateSandboxResponse.DataR\x04data\x12&\n" +
	"\x06status\x18\x02 \x01(\v2\x0e.common.StatusR\x06status\x1aU\n" +
	"\x04Data\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12.\n" +
	"\x05state\x18\x02 \x01(\x0e2\x18.sandbox.v1.SandboxStateR\x05state\"5\n" +
	"\x14DeleteSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"?\n" +
	"\x15DeleteSandboxResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusR\x06status\"8\n" +
	"\x17GetSandboxStatusRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\xa4\x03\n" +
	"\x18GetSandboxStatusResponse\x12=\n" +
	"\x04data\x18\x01 \x01(\v2).sandbox.v1.GetSandboxStatusResponse.DataR\x04data\x12&\n" +
	"\x06status\x18\x02 \x01(\v2\x0e.common.StatusR\x06status\x1a\xa0\x02\n" +
	"\x04Data\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.sandbox.v1.SandboxStateR\x05state\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x12:\n" +
	"\fsandbox_type\x18\x03 \x01(\x0e2\x17.sandbox.v1.SandBoxTypeR\vsandboxType\x12*\n" +
	"\x06config\x18\x04 \x01(\v2\x12.sandbox.v1.ConfigR\x06config\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"\x18\n" +
	"\x16GetSandboxTypesRequest\"\xc5\x01\n" +
	"\x17GetSandboxTypesResponse\x12<\n" +
	"\x04data\x18\x01 \x01(\v2(.sandbox.v1.GetSandboxTypesResponse.DataR\x04data\x12&\n" +
	"\x06status\x18\x02 \x01(\v2\x0e.common.StatusR\x06status\x1aD\n" +
	"\x04Data\x12<\n" +
	"\rsandbox_types\x18\x01 \x03(\x0e2\x17.sandbox.v1.SandBoxTypeR\fsandboxTypes\"C\n" +
	"\x06Config\x129\n" +
	"\vruntimeType\x18\x01 \x01(\x0e2\x17.sandbox.v1.RuntimeTypeR\vruntimeType*L\n" +
	"\tLifeCycle\x12\x15\n" +
	"\x11LIFECYCLE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10LIFECYCLE_ALWAYS\x10\x01\x12\x12\n" +
	"\x0eLIFECYCLE_ONCE\x10\x02*\xb0\x01\n" +
	"\fSandboxState\x12\x19\n" +
	"\x15SANDBOX_STATE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16SANDBOX_STATE_CREATING\x10\x01\x12\x19\n" +
	"\x15SANDBOX_STATE_RUNNING\x10\x02\x12\x1a\n" +
	"\x16SANDBOX_STATE_DELETING\x10\x03\x12\x19\n" +
	"\x15SANDBOX_STATE_DELETED\x10\x04\x12\x17\n" +
	"\x13SANDBOX_STATE_ERROR\x10\x05*l\n" +
	"\vSandBoxType\x12\x15\n" +
	"\x11SANDBOX_TYPE_Base\x10\x00\x12\x13\n" +
	"\x0fSANDBOX_TYPE_FS\x10\x01\x12\x18\n" +
	"\x14SANDBOX_TYPE_BROWSER\x10\x02\x12\x17\n" +
	"\x13SANDBOX_TYPE_CUSTOM\x10\x03*Y\n" +
	"\vRuntimeType\x12\x1b\n" +
	"\x17RUNTIME_TYPE_Containerd\x10\x00\x12\x17\n" +
	"\x13RUNTIME_TYPE_DOCKER\x10\x01\x12\x14\n" +
	"\x10RUNTIME_TYPE_K8S\x10\x022\xe4\x03\n" +
	"\x0eSandboxService\x12p\n" +
	"\rCreateSandbox\x12 .sandbox.v1.CreateSandboxRequest\x1a!.sandbox.v1.CreateSandboxResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/sandbox\x12m\n" +
	"\rDeleteSandbox\x12 .sandbox.v1.DeleteSandboxRequest\x1a!.sandbox.v1.DeleteSandboxResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/api/v1/sandbox\x12v\n" +
	"\x10GetSandboxStatus\x12#.sandbox.v1.GetSandboxStatusRequest\x1a$.sandbox.v1.GetSandboxStatusResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/sandbox\x12y\n" +
	"\x0fGetSandBoxTypes\x12\".sandbox.v1.GetSandboxTypesRequest\x1a#.sandbox.v1.GetSandboxTypesResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/sandbox/typesBO\n" +
	"*com.alibaba.cloud.ai.agent.runtime.sandboxP\x01Z\x1fagent/sandbox/api/sandbox/v1;v1b\x06proto3"

var (
	file_sandbox_v1_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_v1_sandbox_proto_rawDescData []byte
)

func file_sandbox_v1_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_v1_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_v1_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_v1_sandbox_proto_rawDesc), len(file_sandbox_v1_sandbox_proto_rawDesc)))
	})
	return file_sandbox_v1_sandbox_proto_rawDescData
}

var file_sandbox_v1_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_sandbox_v1_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sandbox_v1_sandbox_proto_goTypes = []any{
	(LifeCycle)(0),                        // 0: sandbox.v1.LifeCycle
	(SandboxState)(0),                     // 1: sandbox.v1.SandboxState
	(SandBoxType)(0),                      // 2: sandbox.v1.SandBoxType
	(RuntimeType)(0),                      // 3: sandbox.v1.RuntimeType
	(*CreateSandboxRequest)(nil),          // 4: sandbox.v1.CreateSandboxRequest
	(*CreateSandboxResponse)(nil),         // 5: sandbox.v1.CreateSandboxResponse
	(*DeleteSandboxRequest)(nil),          // 6: sandbox.v1.DeleteSandboxRequest
	(*DeleteSandboxResponse)(nil),         // 7: sandbox.v1.DeleteSandboxResponse
	(*GetSandboxStatusRequest)(nil),       // 8: sandbox.v1.GetSandboxStatusRequest
	(*GetSandboxStatusResponse)(nil),      // 9: sandbox.v1.GetSandboxStatusResponse
	(*GetSandboxTypesRequest)(nil),        // 10: sandbox.v1.GetSandboxTypesRequest
	(*GetSandboxTypesResponse)(nil),       // 11: sandbox.v1.GetSandboxTypesResponse
	(*Config)(nil),                        // 12: sandbox.v1.Config
	(*CreateSandboxResponse_Data)(nil),    // 13: sandbox.v1.CreateSandboxResponse.Data
	(*GetSandboxStatusResponse_Data)(nil), // 14: sandbox.v1.GetSandboxStatusResponse.Data
	(*GetSandboxTypesResponse_Data)(nil),  // 15: sandbox.v1.GetSandboxTypesResponse.Data
	(*common.Status)(nil),                 // 16: common.Status
}
var file_sandbox_v1_sandbox_proto_depIdxs = []int32{
	2,  // 0: sandbox.v1.CreateSandboxRequest.sandbox_type:type_name -> sandbox.v1.SandBoxType
	12, // 1: sandbox.v1.CreateSandboxRequest.config:type_name -> sandbox.v1.Config
	13, // 2: sandbox.v1.CreateSandboxResponse.data:type_name -> sandbox.v1.CreateSandboxResponse.Data
	16, // 3: sandbox.v1.CreateSandboxResponse.status:type_name -> common.Status
	16, // 4: sandbox.v1.DeleteSandboxResponse.status:type_name -> common.Status
	14, // 5: sandbox.v1.GetSandboxStatusResponse.data:type_name -> sandbox.v1.GetSandboxStatusResponse.Data
	16, // 6: sandbox.v1.GetSandboxStatusResponse.status:type_name -> common.Status
	15, // 7: sandbox.v1.GetSandboxTypesResponse.data:type_name -> sandbox.v1.GetSandboxTypesResponse.Data
	16, // 8: sandbox.v1.GetSandboxTypesResponse.status:type_name -> common.Status
	3,  // 9: sandbox.v1.Config.runtimeType:type_name -> sandbox.v1.RuntimeType
	1,  // 10: sandbox.v1.CreateSandboxResponse.Data.state:type_name -> sandbox.v1.SandboxState
	1,  // 11: sandbox.v1.GetSandboxStatusResponse.Data.state:type_name -> sandbox.v1.SandboxState
	2,  // 12: sandbox.v1.GetSandboxStatusResponse.Data.sandbox_type:type_name -> sandbox.v1.SandBoxType
	12, // 13: sandbox.v1.GetSandboxStatusResponse.Data.config:type_name -> sandbox.v1.Config
	2,  // 14: sandbox.v1.GetSandboxTypesResponse.Data.sandbox_types:type_name -> sandbox.v1.SandBoxType
	4,  // 15: sandbox.v1.SandboxService.CreateSandbox:input_type -> sandbox.v1.CreateSandboxRequest
	6,  // 16: sandbox.v1.SandboxService.DeleteSandbox:input_type -> sandbox.v1.DeleteSandboxRequest
	8,  // 17: sandbox.v1.SandboxService.GetSandboxStatus:input_type -> sandbox.v1.GetSandboxStatusRequest
	10, // 18: sandbox.v1.SandboxService.GetSandBoxTypes:input_type -> sandbox.v1.GetSandboxTypesRequest
	5,  // 19: sandbox.v1.SandboxService.CreateSandbox:output_type -> sandbox.v1.CreateSandboxResponse
	7,  // 20: sandbox.v1.SandboxService.DeleteSandbox:output_type -> sandbox.v1.DeleteSandboxResponse
	9,  // 21: sandbox.v1.SandboxService.GetSandboxStatus:output_type -> sandbox.v1.GetSandboxStatusResponse
	11, // 22: sandbox.v1.SandboxService.GetSandBoxTypes:output_type -> sandbox.v1.GetSandboxTypesResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_sandbox_v1_sandbox_proto_init() }
func file_sandbox_v1_sandbox_proto_init() {
	if File_sandbox_v1_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_v1_sandbox_proto_rawDesc), len(file_sandbox_v1_sandbox_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_v1_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_v1_sandbox_proto_depIdxs,
		EnumInfos:         file_sandbox_v1_sandbox_proto_enumTypes,
		MessageInfos:      file_sandbox_v1_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_v1_sandbox_proto = out.File
	file_sandbox_v1_sandbox_proto_goTypes = nil
	file_sandbox_v1_sandbox_proto_depIdxs = nil
}
